### ISSUE TITLE
consider surface based S

### ISSUE THREAD

**Issue by AnttiHaerkoenen** [pysal/segregation#102]
Described in https://doi.org/10.1111/j.1538-4632.2007.00699.x

**Comment by renanxcortes** [comment]
> Described in https://doi.org/10.1111/j.1538-4632.2007.00699.x

We definitely want to continue improving the surface based measures. But, it is worth to mention that the approach followed in https://github.com/pysal/segregation/blob/master/notebooks/network_measures.ipynb is a surface based segregation measure!

**Comment by AnttiHaerkoenen** [comment]
I implemented this in my own project. Maybe I could contribute something?

**Comment by renanxcortes** [comment]
> I implemented this in my own project. Maybe I could contribute something?

Sure, feel free to contribute!

**Comment by knaaptime** [comment]
would definitely welcome a PR :)

**Comment by knaaptime** [comment]
which index did you want to use? right now, you can use `SpatialDissim`, `SpatialInformationTheory`, or `SpatialDivergence` and pass a libpysal Kernel weights object to get a surface-based measure, exactly as described in the O'Sullivan and Wong paper. We haven't finished [extending](https://github.com/pysal/segregation/issues/104) that to other indices indices yet though

**Comment by AnttiHaerkoenen** [comment]
> which index did you want to use? right now, you can use `SpatialDissim`, `SpatialInformationTheory`, or `SpatialDivergence` and pass a libpysal Kernel weights object to get a surface-based measure, exactly as described in the O'Sullivan and Wong paper.

I want to use S which is not the same as D, although they are related as shown in formula 16 of their paper

**Comment by renanxcortes** [comment]
Closed as this was added in https://github.com/pysal/segregation/pull/116.
