### ISSUE TITLE
handling nans/missing values

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#105]
the following will result in a np.nan value for the `statistic` because `n_nonhsip_black_persons` has NaN values. 

```python
dc = Community(source='ltdb', cbsafips='47900')
dc = dc.tracts.merge(dc.census,left_on='geoid', right_index=True)
dc_sd = SpatialDissim(dc, group_pop_var='n_nonhisp_black_persons', total_pop_var='n_total_pop')
```
We should either move to more robust numpy operators that handle nans, or check whether there are any present in `group_pop_var` or `total_pop_var` and raise accordingly

**Comment by renanxcortes** [comment]
Agreed! So, for this, I think that what makes sense is to build a utility function inside util that would check for NaN in either group_pop_var or total_pop_var and then, warn the user that these values will be dropped with something like:
```
df.dropna(subset=[group_pop_var, total_pop_var])
```

**Comment by knaaptime** [comment]
what if we just used `np.nansum`s and the like, thus avoiding the need to drop na's in the first place?

**Comment by renanxcortes** [comment]
> the following will result in a np.nan value for the `statistic` because `n_nonhsip_black_persons` has NaN values.
> 
> ```python
> dc = Community(source='ltdb', cbsafips='47900')
> dc = dc.tracts.merge(dc.census,left_on='geoid', right_index=True)
> dc_sd = SpatialDissim(dc, group_pop_var='n_nonhisp_black_persons', total_pop_var='n_total_pop')
> ```
> 
> We should either move to more robust numpy operators that handle nans, or check whether there are any present in `group_pop_var` or `total_pop_var` and raise accordingly

Does the statistic attribute is NaN also if you use only `Dissim` (and not the spatial version)?

**Comment by renanxcortes** [comment]
> what if we just used `np.nansum`s and the like, thus avoiding the need to drop na's in the first place?

Yes, perhaps this would make more sense and more elegant! In this case, we need to make a little `refactorization` in each class for other operations in addition to the numpy sum.

**Comment by renanxcortes** [comment]
I ran into this error with Myrna. I realized that it is possible that some lines have `group_pop_var` with NaN and `total_pop_var` with non-NaN in the same line which can lead to problems when dealing with robust numpy aggregation (for example, the total number of a minority group and total population can be from a different number of tracts). In this case, I think what is best is to add a utility function that will raise an informative error if there are any missing value in the variables of the input data or drop the missing rows where this happens and warn the user.

**Comment by knaaptime** [comment]
We should just be able to check for tot_pop_var. 

If there's total population but group_pop_var is Nan, then it should really be 0

**Comment by renanxcortes** [comment]
> We should just be able to check for tot_pop_var.
> 
> If there's total population but group_pop_var is Nan, then it should really be 0

Hm, I don't think that it would be good to assume zero an unknown NaN (even having the total population value). Suppose you have a data set you know the amount of people in a unit (`total_pop_var`), but doesn't know the number of the minority people (even though there may have people there), therefore, Inputting zero may affect the index.

**Comment by renanxcortes** [comment]
I'm misusing the term `NaN`... what I want to refer is actually NA (not available).

**Comment by knaaptime** [comment]
i understand the scenario you're describing, but i think that's pretty unlikely. Almost always, the group_pop_var and the total_pop_var are going to come from the same data source, in which case a non-nan total_pop_var implies a 0 when group_pop_var is nan

**Comment by knaaptime** [comment]
i'd advocate a simple check with a warning that ```len(np.isnan(group_pop_var) != len(np.isnan(total_pop_var)```, and describes that we'll treat group_pop_var as 0 in cases where total_pop_var.notnull() but group_pop_var.is_null()

**Comment by renanxcortes** [comment]
Yes, that kinda makes sense raising a warning. I just wonder also if the `core_data` attribute will have the inputted zeros or the original data.

**Comment by knaaptime** [comment]
Oh good point. I think we use `np.nansum`s internally so they are effectively 0 but leave the `core_data` exactly as input
