### ISSUE TITLE
plots should return fig/ax for composability

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#108]
most of the plotting functionality started as a convenience for ourselves, but now that we're using them more often we need to make sure we're returning at least the axes object so users can edit/save/combine plots, etc

**Comment by renanxcortes** [comment]
Yes, got it... What you're referring is that right now we cannot do something like:

```
import unittest
import libpysal
import geopandas as gpd
import numpy as np
from segregation.aspatial import Dissim
from segregation.decomposition import DecomposeSegregation

s_map = gpd.read_file(libpysal.examples.get_path("sacramentot2.shp"))
index1 = Dissim(s_map, 'HISP_', 'TOT_POP')
index2 = Dissim(s_map, 'BLACK_', 'TOT_POP')
res = DecomposeSegregation(index1, index2, counterfactual_approach = "composition")
ax = res.plot(plot_type = 'cdfs')
ax.set_title('Other Title')
```

Right?

**Comment by knaaptime** [comment]
exactly

**Comment by renanxcortes** [comment]
Partilaly solved with https://github.com/pysal/segregation/pull/109 for the inference wrappers. There's still plotting methods for the decomposition and for some indexes such as Concentration Profile and Spatial Concentration Profile.
