### ISSUE TITLE
Building Error (after tqdm inclusion?)

### ISSUE THREAD

**Issue by renanxcortes** [pysal/segregation#110]
I think that after adding tqdm in https://github.com/pysal/segregation/pull/109, TravisCI broke and the error log is:

```
Using /home/travis/build/pysal/segregation/miniconda/envs/test-env/lib/python3.7/site-packages
Finished processing dependencies for segregation==1.1.0
The command "python setup.py install" exited with 0.
21.95s$ nosetests -v segregation --with-coverage
Failure: ImportError (libcfitsio.so.5: cannot open shared object file: No such file or directory) ... ERROR
======================================================================
ERROR: Failure: ImportError (libcfitsio.so.5: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
```

Not really sure how to to debug this. Any ideas?

**Comment by knaaptime** [comment]
i saw... weird C lib error. no idea what this is about. tests passed fine on my branch and on the PR, so im hoping this is just a fleeting conda-forge thing? 🤷‍♂️

**Comment by renanxcortes** [comment]
> i saw... weird C lib error. no idea what this is about. tests passed fine on my branch and on the PR, so im hoping this is just a fleeting conda-forge thing? 🤷‍♂️

Yes, I also nosetested it locally and it ran smoothly!

**Comment by knaaptime** [comment]
ok, so I pushed these changes last night and the tests passed fine. I just tried restarting that build, and now they'rea failing. I also tried `sudo -E apt install libcfitsio-dev -y`, which works perfectly on my linux box, but failed on travis with 

```
The command "sudo -E apt install libcfitsio-dev -y" failed and exited with 100 during .
```

that [appears](https://github.com/travis-ci/travis-ci/issues/7987) to be an apt/gpg error, which is probably on travis's end, so I think we're ok here and just need to wait a bit for a fix upstream

**Comment by renanxcortes** [comment]
> ok, so I pushed these changes last night and the tests passed fine. I just tried restarting that build, and now they'rea failing. I also tried `sudo -E apt install libcfitsio-dev -y`, which works perfectly on my linux box, but failed on travis with
> 
> ```
> The command "sudo -E apt install libcfitsio-dev -y" failed and exited with 100 during .
> ```
> 
> that [appears](https://github.com/travis-ci/travis-ci/issues/7987) to be an apt/gpg error, which is probably on travis's end, so I think we're ok here and just need to wait a bit for a fix upstream

So, we should open a PR on segregation that would try to apt install `libcfitsio-dev`?

**Comment by renanxcortes** [comment]
Fixed as the build as ok in Travis's side.
