### ISSUE TITLE
Swap to more robust tests that rely on numpy seeds

### ISSUE THREAD

**Issue by renanxcortes** [pysal/segregation#123]
Segregation on PySAL started to fail on travis https://travis-ci.org/pysal/pysal/jobs/566597373#L2405

This is due to indexes that rely on simulations and, therefore, numpy seeds. Travis now is building using numpy 1.17.0 (released 6 days ago). Some features were changed in the generating process of the seeds as you can read in https://github.com/numpy/numpy/releases.

![image](https://user-images.githubusercontent.com/22593188/62322131-34a79e00-b459-11e9-9c19-27c6ee572ca3.png)

I upgraded locally my numpy to 1.17.0 (previously it was 1.16.0) and, now, my seed generates the values that match the new tests (7 digit precision).

Since I don't think it is a good thing the rely on the numpy version for the simulation-based tests... I think I'll increase the degree of tolerance of all tests and rewrite the tests (inference based also will change since they also rely on numpy seeds).

**Comment by knaaptime** [comment]
resolved by #125?

**Comment by renanxcortes** [comment]
Yes, thank you!
