### ISSUE TITLE
Strange non-corresponding legend on output (Out)when running indexes

### ISSUE THREAD

**Issue by MyrnaSastre** [pysal/segregation#135]
When running segregation indexes, I get a non-corresponding output legend (Out).  It repeats the same output line: "segregation.spatial.spatial_indexes.SpatialDissim" regardless if the index has change...  here an example of two different indexes, same Out legend:
<img width="1123" alt="Screen Shot 2019-08-22 at 7 20 42 PM" src="https://user-images.githubusercontent.com/30789214/63562496-adf35780-c512-11e9-9bce-6f1e01986708.png">

This seems to be the default Output line in my local results... in every index...but this is not the case in the examples from the notebook.  

Any ideas as to what can be the problem in my local version?  Thanks!!!

**Comment by knaaptime** [comment]
it looks like you're estimating three different indices: 

- distance decay exposure stored in a variable called `index_DDE_g`
- delta, stored in a variable called `index_DELTA_g`
- dissimilarity, stored in a variable called `index`

in the screenshot, you're calling `type(index)`, which is checking the type of the dissimilarity index each time. If you want to take a look at the others, you need to change the variable. 
 e.g. 

```python
type(index)
type(index_DDE_g)
type(index_DELTA_g)
```
should show you different results.

**Comment by MyrnaSastre** [comment]
I see...  thanks Eli!

**Comment by knaaptime** [comment]
of course. does that solve your issue?

**Comment by MyrnaSastre** [comment]
Yes. The legend of output changes, but the index value is the same.  Here an example before and after correcting the index name:
<img width="1131" alt="Screen Shot 2019-08-22 at 9 44 55 PM" src="https://user-images.githubusercontent.com/30789214/63567403-4b0bbb80-c526-11e9-8294-83bb97d63d4b.png">
<img width="1132" alt="Screen Shot 2019-08-22 at 9 45 24 PM" src="https://user-images.githubusercontent.com/30789214/63567407-51019c80-c526-11e9-87a6-ed17874051a1.png">

so, the estimation seems to be robust even if you don't change the type()

**Comment by renanxcortes** [comment]
> Yes. The legend of output changes, but the index value is the same. Here an example before and after correcting the index name:
> <img alt="Screen Shot 2019-08-22 at 9 44 55 PM" width="1131" src="https://user-images.githubusercontent.com/30789214/63567403-4b0bbb80-c526-11e9-8294-83bb97d63d4b.png">
> <img alt="Screen Shot 2019-08-22 at 9 45 24 PM" width="1132" src="https://user-images.githubusercontent.com/30789214/63567407-51019c80-c526-11e9-87a6-ed17874051a1.png">
> 
> so, the estimation seems to be robust even if you don't change the type()

In the first cell, you create the object called `index_ACO` but check the type of `index`. The name of the objects should be the same.

In addition, the estimation has nothing to do with the type. This is just to show the user the name of the class that was built that depends of the function it calls.

**Comment by MyrnaSastre** [comment]
Yes. I get that those names should be the same. That's what I was trying to explain above. I corrected the type() of the index in the second screenshot, but since you mentioned that it should show different results, I just wanted to show you the results in the two versions, one without the correction and the second one corrected. Thanks for the clarification that the estimation is independent.  It is clear now... thanks again!

**Comment by renanxcortes** [comment]
> Yes. I get that those names should be the same. That's what I was trying to explain above. I corrected the type() of the index in the second screenshot, but since you mentioned that it should show different results, I just wanted to show you the results in the two versions, one without the correction and the second one corrected. Thanks for the clarification that the estimation is independent. It is clear now... thanks again!

Ok, cool! Glad it is clear now!! :)
