### ISSUE TITLE
Website is not rendering correctly

### ISSUE THREAD

**Issue by sjsrey** [pysal/segregation#149]
![image](https://user-images.githubusercontent.com/118042/90278202-de1ac100-de1b-11ea-9ffb-79982417c529.png)

**Comment by knaaptime** [comment]
on https://segregation.readthedocs.io/en/latest/index.html ?

**Comment by renanxcortes** [comment]
hm.. weird.. I think I'm getting it properly:

![image](https://user-images.githubusercontent.com/22593188/90278990-bbe66a80-de3e-11ea-8404-10d03a5fb64f.png)

**Comment by jGaboardi** [comment]
See @martinfleis's [comment](https://gitter.im/pysal/pysal?at=5f36c0924d3fd87ee7d49d6c) on gitter:

> It looks like a missing `.nojekyll`.
