### ISSUE TITLE
error when installing using pip

### ISSUE THREAD

**Issue by lmikaelian** [pysal/segregation#15]
Hi, I've been getting an error when I try to install segregation using option 2, the pip install option.

`Command "python setup.py egg_info" failed with error code 1 in C:\Users\lm13n\AppData\Local\Temp\pip-install-r6y591a0\fiona\`

I am installing into an Anaconda Python 3.6.8 environment on Windows 10. However, option 1 installs successfully.

Thanks, 
Levon

**Comment by renanxcortes** [comment]
Hello, Levon, thanks for pointing that out. 
I tried here in my machine which is also a Windows 10 and it went fine. Perhaps, it is something related to your setuptools. 

Could you try to run:

`pip install --upgrade setuptools`

And then try again the first option?

Best,
Renan

**Comment by lmikaelian** [comment]
Hi Renan!

Thanks for getting back to me so quickly! I tried this and still get that error.

- Levon

**Comment by renanxcortes** [comment]
Ok, can you paste here the full log of what is going on when you run this pip install?

**Comment by lmikaelian** [comment]
Sure!

`Collecting git+https://github.com/pysal/segregation
  Cloning https://github.com/pysal/segregation to c:\users\lm13n\appdata\local\temp\pip-req-build-rmm79a06
Requirement already satisfied: pandas in c:\programdata\anaconda2\envs\python3\lib\site-packages (from segregation==1.0.1) (0.24.2)
Collecting geopandas (from segregation==1.0.1)
  Using cached https://files.pythonhosted.org/packages/f0/5d/916b7268ef551fa9647ce12220e9a68006374f1ce5b0ddaf1cd0df2880b7/geopandas-0.4.1-py2.py3-none-any.whl
Requirement already satisfied: matplotlib in c:\programdata\anaconda2\envs\python3\lib\site-packages (from segregation==1.0.1) (3.0.3)
Collecting scikit-learn (from segregation==1.0.1)
  Using cached https://files.pythonhosted.org/packages/e7/e4/56757c30853899077cf042f78fb981c0b60f7af4e7a54ca18328b80e0bff/scikit_learn-0.20.3-cp36-cp36m-win_amd64.whl
Requirement already satisfied: seaborn in c:\programdata\anaconda2\envs\python3\lib\site-packages (from segregation==1.0.1) (0.9.0)
Requirement already satisfied: numpy in c:\programdata\anaconda2\envs\python3\lib\site-packages (from segregation==1.0.1) (1.16.2)
Requirement already satisfied: scipy in c:\programdata\anaconda2\envs\python3\lib\site-packages (from segregation==1.0.1) (1.2.1)
Requirement already satisfied: libpysal in c:\programdata\anaconda2\envs\python3\lib\site-packages (from segregation==1.0.1) (4.0.1)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda2\envs\python3\lib\site-packages (from pandas->segregation==1.0.1) (2019.1)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\programdata\anaconda2\envs\python3\lib\site-packages (from pandas->segregation==1.0.1) (2.8.0)
Collecting shapely (from geopandas->segregation==1.0.1)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
Collecting pyproj (from geopandas->segregation==1.0.1)
  Using cached https://files.pythonhosted.org/packages/91/39/28b9ce4c7a81c5d10d2002de3a8ac1ce49ba19fbf07e16be2772bd5d18b3/pyproj-2.1.3-cp36-cp36m-win_amd64.whl
Collecting fiona (from geopandas->segregation==1.0.1)
  Using cached https://files.pythonhosted.org/packages/41/9d/63696e7b1de42aad294d4781199a408bec593d8fdb80a2b4a788c911a33b/Fiona-1.8.6.tar.gz
    Complete output from command python setup.py egg_info:
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\lm13n\AppData\Local\Temp\pip-install-ddhasm5f\fiona\`

**Comment by jGaboardi** [comment]
@lmikaelian can you edit your comment with "```" before the first line of output and "```" after the last line? It will be displayed as a single block of "code" and will be much easier to read.

**Comment by lmikaelian** [comment]
Thanks @jGaboardi

**Comment by jGaboardi** [comment]
@lmikaelian it is likely as issue with the `geopandas`/`fiona`/etc. install.

`geopandas` (and all it's dependencies) should only be [installed via `conda-forge`](http://geopandas.org/install.html) to prevent conflicts. I strongly recommend creating and working in environments so that when something get screwy (as it always  does), it is easy to start over without messing up your bas python install.

**Comment by jGaboardi** [comment]
try this:
```
$ conda clean --all -y
$ conda update -n base conda
$ conda config --set channel_priority strict
$ conda create --name Levon_Env python=3.6 geopandas --channel conda-forge --yes
$ source activate Levon_Env
$ pip install git+https://github.com/pysal/segregation

**Comment by lmikaelian** [comment]
@jGaboardi reinstalling geopandas the recommended way worked! I'll try your snippet now.

**Comment by lmikaelian** [comment]
@jGaboardi I get this error when I run `conda create --name Levon_Env python=3.6 geopandas --channel conda-forge --yes`

```WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - geopandas
Use "conda search <package> --info" to see the dependencies for each package.```

**Comment by jGaboardi** [comment]
Did you follow the prompts before that exactly? This works for `MacOS`, but may be different for `Windows`.

**Comment by lmikaelian** [comment]
@jGaboardi I think I did. I'll try it again in a little while.

**Comment by jGaboardi** [comment]
geopandas/geopandas#941
geopandas/geopandas#793

**Comment by jGaboardi** [comment]
conda/conda#7656

**Comment by renanxcortes** [comment]
> @jGaboardi I think I did. I'll try it again in a little while.

Now, you can try with:

```
pip install segregation
```

**Comment by lmikaelian** [comment]
@renanxcortes @jGaboardi  I've cleaned up my Python situation. Using Miniconda and environments now and everything works or is easily fixed by installing things in different order

**Comment by renanxcortes** [comment]
Ok, nice, happy to hear that! I'll update the Readme file, so if a user experiences this problem again he can take a look at this issue.
Thanks!
