### ISSUE TITLE
Dissimilarity Index API typo

### ISSUE THREAD

**Issue by federicoricca** [pysal/segregation#167]
In the API page for `aspatial.Dissim` ([here](https://pysal.org/segregation/generated/segregation.aspatial.Dissim.html#segregation.aspatial.Dissim)) there is a typo in the column names of the example. The tractable dataframe should retain `'nhblk10'` rather than `'tractid'`, namely:

`df = census_2010.loc[census_2010.county == "Riverside County"][['pop10','nhblk10']]`

and similarly afterwards:

`dissim_index = Dissim(df, 'nhblk10', 'pop10')` 

Hope this helps!

**Comment by renanxcortes** [comment]
> In the API page for `aspatial.Dissim` ([here](https://pysal.org/segregation/generated/segregation.aspatial.Dissim.html#segregation.aspatial.Dissim)) there is a typo in the column names of the example. The tractable dataframe should retain `'nhblk10'` rather than `'tractid'`, namely:
> 
> `df = census_2010.loc[census_2010.county == "Riverside County"][['pop10','nhblk10']]`
> 
> and similarly afterwards:
> 
> `dissim_index = Dissim(df, 'nhblk10', 'pop10')`
> 
> Hope this helps!

Thanks for pointing that out! Indeed, this typo happens in the documentation of other indexes too.

**Comment by knaaptime** [comment]
resolved by #161
