### ISSUE TITLE
consider multi-group segregation indexes

### ISSUE THREAD

**Issue by renanxcortes** [pysal/segregation#17]
Consider implement the multi-group indexes. A good start can be the following (Luc Anselin questioned that to me at the AAG 2019):
"Reardon, Sean F., and Glenn Firebaugh. "Measures of multigroup segregation." Sociological methodology 32.1 (2002): 33-67."

**Comment by knaaptime** [comment]
i think this is resolved?

**Comment by renanxcortes** [comment]
Yes! Thanks for pointing that out!
