### ISSUE TITLE
add deprecation layer for 2.0

### ISSUE THREAD

**Issue by sjsrey** [pysal/segregation#171]
#161 

See the mapping of old to new [here](https://docs.google.com/spreadsheets/d/1K-iibhqkG5y4aYnCy5iz1KMB8rPuwYPqGjIRyaKFF4k/edit#gid=0).

**Comment by sjsrey** [comment]
Work in progress is [here](https://github.com/sjsrey/segregation/tree/dep2.0)

**Comment by sjsrey** [comment]
I think most of the old methods are now covered by deprecation warnings in 2.0.

One class that I don't see mapped to a new version is `spatial,SpatialDivergence` @knaaptime is this correct that we are dropping this in 2.0 or did I miss a mapping to a new class?

**Comment by sjsrey** [comment]
TODO

- [ ] document what modules/functions need to be removed when 2.2.0 is released
- [ ] Removal
    - [ ] [network](https://github.com/sjsrey/segregation/tree/dep2.0//segregation/network)
    - [ ] [spatial](https://github.com/sjsrey/segregation/tree/dep2.0/segregation/spatial)
    - [ ] [aspatial](https://github.com/sjsrey/segregation/tree/dep2.0/segregation/aspatial)
 - [ ] Modify
     - [ ] [__init__.py](https://github.com/sjsrey/segregation/blob/dep2.0/segregation/__init__.py#L10)
     - [ ] [util.py](https://github.com/sjsrey/segregation/blob/dep2.0/segregation/util/util.py#L255)

**Comment by knaaptime** [comment]
awesome, thank you!

>One class that I don't see mapped to a new version is spatial,SpatialDivergence @knaaptime is this correct that we are dropping this in 2.0 or did I miss a mapping to a new class?

musta missed it on accident. It collapses into `multigroup.MultiDivergence`

**Comment by knaaptime** [comment]
resolved by #161
