### ISSUE TITLE
function to calculate segregation profiles

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#19]
in [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2831394/pdf/dem-45-0489.pdf) piece, Reardon et al calculate multiscalar segregation profiles by calculating several spatial information theory indices with different specifications of W (increasing in kernel distance). By calculating the ratio of SIT w/ a small-distance W against SIT w/ a large-distance W, they can decompose segregation as a function of scale

> "In particular, we find that the proportion of micro-scale segregation that is due to macro-scale segregation ranges between 20% and 80% across these 40 metropolitan areas, with macro-scale segregation generally accounting for a larger share of white-black segregation than of white-Hispanic or white Asian segregation. This heterogeneity raises a number of >additional questions that we (and other scholars, we hope) will address in subsequent research."

Now that we have SIT in the library, we could provide a function to do the same. This would also serve to help movtivate the use of network-based kernel weights, like discussed [here](https://gist.github.com/knaaptime/538584080e49dcc424568690b915cbe7)

**Comment by renanxcortes** [comment]
Interesting! We would just need to adapt the SIT index (or even other from Reardon, 2004) to kernel-based indexes... later, this decomposition could be added to the `decompose_segregation` wrapper... where the user could decompose according to, for example, shapleys components or scale given from different W's.

**Comment by knaaptime** [comment]
I think all we need to do is allow SIT to accept any kind of W. Then we could use pysal's [kernel weights](https://libpysal.readthedocs.io/en/latest/generated/libpysal.weights.Kernel.html#libpysal.weights.Kernel) or implement the network kernel weights using either pandana or https://github.com/GeoDaCenter/spatial_access

**Comment by knaaptime** [comment]
![image](https://user-images.githubusercontent.com/4213368/57412954-66d19880-71a7-11e9-9051-d7cc0c1433c3.png)

the idea would be that by using street networks to form the kernel, we're answering Fowler's call for 'better measures of the local environment'

**Comment by knaaptime** [comment]
resolved by #75
