### ISSUE TITLE
`master` to `main` for default branch

### ISSUE THREAD

**Issue by jGaboardi** [pysal/segregation#204]
Also might be a good time to change the default branch from `master` to `main`. This has become trivial to do with the "rename default branch" functionality that also updates open pull requests.

<img width="1419" alt="Screenshot 2022-12-12 at 3 23 26 PM" src="https://user-images.githubusercontent.com/8590583/207147112-6e8f6106-2086-4fb1-bd66-c02bf13a0734.png">

**Comment by knaaptime** [comment]
done, i think

**Comment by jGaboardi** [comment]
Yep, just remember to update your own remote to `main` and should be squared away.
