### ISSUE TITLE
publish workflow needs updating

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#215]
the [setup.py](https://github.com/pysal/segregation/blob/ba475acbfc1cccdb59fa3e829e00f422bc220b3d/.github/workflows/upload_package.yml#L23) line [doesnt work](https://github.com/pysal/segregation/actions/runs/4866743356)  with pyproject.toml (since setup.py isnt around anymore). It [looks like](https://github.com/pypa/setuptools_scm/issues/487) we need to preinstall the package before using sdist? Not sure exactly. Have you done a release of spopt with the new machinery @jGaboardi ?

**Comment by jGaboardi** [comment]
We are using similar actions over in [`spaghetti`](https://github.com/pysal/spaghetti/blob/main/.github/workflows/release_and_publish.yml#L38) and [`spopt`](https://github.com/pysal/spopt/blob/main/.github/workflows/release_and_publish.yml#L29), so I suspect they may fail next time we cut a release. Perhaps let's try using the action @martinfleis cooked up over in [`momepy`](https://github.com/pysal/momepy/blob/main/.github/workflows/release_to_pypi.yml)?
