### ISSUE TITLE
Interaction Index Still Supported?

### ISSUE THREAD

**Issue by PFurst2000** [pysal/segregation#223]
A few months ago i ran a script for interaction index that started with the following code "from segregation.singlegroup import Interaction" but now it doesn't work. Was the package updated recently? I assume I need to replace the "from segregation.singlegroup" with something like from "segregation.aspatial" or "from segregation.spatial" but I cant identify the correct code. Is the Interaction Index still supported or categorized as something else?

**Comment by jGaboardi** [comment]
@PFurst2000 Can you provide both the version of `segregation` where that import succeeded and the version you are running now?

**Comment by knaaptime** [comment]
sounds like something's off. The API hasn't changed and the tests are passing (and i just imported here, just to be sure). Maybe you have an old version?

**Comment by PFurst2000** [comment]
I had to delete my hard drive since I originally ran the queries so I am not sure which version I used. I downloaded it around March 2023. What I noticed was the new version I downloaded requires a script that starts with "from segregation.aspatial import Dissim"  for indices such as the dissimilarity index  while previously my codes started with "from segregation.singlegroup import Dissim" or "from segregation.singlegroup import Interaction"

My old interaction index started as follows:
import pandas as pd
import geopandas as gpd
from segregation.singlegroup import Interaction

# read in the shapefile
gdf = gpd.read_file...

**Comment by knaaptime** [comment]
you got downgraded; that's the old api. do 

```python
import segregation
segregation.__version__
```
and tell us what you see. the current version is 2.5, but you've got to be on 1.x

**Comment by PFurst2000** [comment]
that makes sense. i think I downloaded it directly from anaconda, assuming
it would the latest package.

**Comment by PFurst2000** [comment]
yeah its 1.3.0

**Comment by knaaptime** [comment]
sounds good. if you update to the latest, your old script should work. Otherwise, you can use the old api (if for some reason you are stuck on 1.3) and jsut import like you said i.e. from `segregation.aspatial import Interaction`. As long as you arent passing a `W` or a `Network`, you'll get the same results.

Feel free to respond here if you're still having trouble but im going to close this as resolved
