### ISSUE TITLE
add DOI

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#32]
i turned on the zenodo integration for this repo, so the next github release should get tagged automatically with a DOI. Once that happens, we should add the badge to the repo

To Do:
- [ ] cut github release
- [ ] add badge to readme

**Comment by renanxcortes** [comment]
Hm.. not sure if I followed because I never worked with this integration.. is this going to be for the 1.0.7 release or the current one (1.0.6)?

**Comment by knaaptime** [comment]
i just turned it on this morning, so it would activate for the 1.0.7

**Comment by knaaptime** [comment]
i dont think its super urgent, so i'd just intended for this as a reminder to add to the readme once we do the next release

**Comment by renanxcortes** [comment]
This is resolved in the 1.1.0 release.
