### ISSUE TITLE
parallelization simulation based indexes and inference wrappers

### ISSUE THREAD

**Issue by renanxcortes** [pysal/segregation#35]
- Some indexes such as Modified Dissimilarity (Dct), Modified Gini (Gct) and Bias-Corrected Dissimilarity (Dbc) could be leveraged to work in parallel since they rely on independent draws of probability distributions and recalculating the index.

- Also, the inference wrappers (`Infer_Segregation` and `Compare_Segregation`) could be leveraged to work in parallel since they rely on independent simulations framework.

A possibility to implement is to use Dask (https://github.com/dask/dask), concurrent.futures (https://docs.python.org/3/library/concurrent.futures.html), etc.

**Comment by knaaptime** [comment]
[this](https://stackoverflow.com/questions/24345637/why-doesnt-numpy-random-and-multiprocessing-play-nice) might be relevant

which also raises the issue that we might want to allow a `seed` argument in the current implementation

**Comment by renanxcortes** [comment]
I was just surfing on the web reading some posts and just wondering if we could use some kind of just-in-time for these functions: http://numba.pydata.org/numba-doc/0.17.0/user/jit.html or soemthing similar to what it is possible to do in R with for loops with the compiler package: https://www.r-statistics.com/2012/04/speed-up-your-r-code-using-a-just-in-time-jit-compiler/

**Comment by knaaptime** [comment]
i'm familiar with numba in concept but never been sure what kind of code its able to speed up. maybe we could try some speed tests?

**Comment by knaaptime** [comment]
solved for inference classes by #174

**Comment by knaaptime** [comment]
resolved by #183
