### ISSUE TITLE
consider tqdm instead of print statements for simulations

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#99]
[these](https://github.com/pysal/segregation/blob/286fbac905370e9058eb0301ca5d6f25b1db713a/segregation/inference/inference_wrappers.py#L111) print statements dont show up in jupyterlab for me so I end up with a ton of blank space in the notebook and no indication of what's happening. 

What about shifting over to [tqdm.auto](https://tqdm.github.io/) which would be a bit more aesthetically pleasing and robust?

**Comment by renanxcortes** [comment]
Sure, definitely +1 for that. I didn't know it didn't show on JupyterLab. I just wanted to avoid some possible dependency crashing using `tqdm` as I already experienced before in other packages.

**Comment by knaaptime** [comment]
i'm not sure its a jupyterlab issue per se, could be a unix-y thing (`\n` vs `\r` ?) but either way...

**Comment by renanxcortes** [comment]
This was merged in https://github.com/pysal/segregation/pull/109.
